[build]
command = "next build"
publish = ".next"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../"

[dev]
framework = "#static"

[[plugins]]
package = "./local-plugin"

[[plugins]]
package = "@netlify/plugin-local-install-core"
