name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 10
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_DEPLOY: local
        with:
          config: video=false
          config-file: false
          project: ./src
